name: flutter_autocomplete_text_field
description: Flutter autocomplete text field.
version: 0.0.1
homepage: http://github.com/svipas/flutter_autocomplete_text_field
repository: http://github.com/svipas/flutter_autocomplete_text_field
issue_tracker: http://github.com/svipas/flutter_autocomplete_text_field/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
